name: ci-cd

on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "php:8"
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install dependencies
        run: composer install

      - name: Run linter
        run: ./vendor/bin/phpstan analyse src tests

      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: contains('refs/heads/master', github.ref)
        with:
          username: laurafau
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: If on `master` Build and push Docker image
        uses: docker/build-push-action@v4
        if: contains('refs/heads/master', github.ref)
        with:
          push: true
          context: ./
          tags: laurafau/companies:latest
